### ISSUE TITLE
Error TypeError: Cannot read property 'length' of null while analyzing page.

### ISSUE THREAD

**Issue by mckamey** [madrobby/dom-monster#19] opened 2011-01-13 18:35 UTC
FYI, I tried running the bookmarklet on the home feed of twitter.com and the last "info" item was this:

"Error TypeError: Cannot read property 'length' of null while analyzing page. Please let the DOM Monster know about this problem!"

Using Chome 8 on Windows:

Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/534.10 (KHTML, like Gecko) Chrome/8.0.552.224 Safari/534.10

**Comment by madrobby** [comment] 2011-01-13 19:28
Works for me on twitter and Chrome 8 for Mac. Can you reproduce this?

**Comment by mckamey** [comment] 2011-01-13 19:39
Yes, happens every time. The analysis completes fine but it says to report the issue at the bottom.

The expression stylesheets[0].cssRules evaluates to null at this line:

https://github.com/madrobby/dom-monster/blob/e89db4ddda71ac2989c5a2e1ba0a632a06b4e4ff/src/dommonster.js#L252

**Comment by madrobby** [comment] 2011-01-13 19:49
should be fixed with https://github.com/madrobby/dom-monster/commit/db609b5e09358252a63d80d5d2f33fa99dfbefa8

**Closed as completed** 2011-01-14 03:39 UTC
