### ISSUE TITLE
Object '#' has no method toLowerCase while analyzing page

### ISSUE THREAD

**Issue by keithnorm** [madrobby/dom-monster#29] opened 2011-01-26 21:40 UTC
Just started getting this error while analyzing groupon.com. Worked fine last time I tried it a few days ago. http://cl.ly/0D3I2T331b2V2i09020u

**Comment by madrobby** [comment] 2011-01-26 22:18
Hey there. I can't reproduce this. Please let us know the exact browser your are using.

I'm also working on making it easier to debug the DOM Monster (by providing info you can paste in here!).

**Comment by keithnorm** [comment] 2011-01-26 22:20
I'm on Chrome 10.0.642.2 dev. Maybe it has something to do with the dev channel of Chrome, that is something I changed since using DOM monster last.

**Comment by keithnorm** [comment] 2011-01-26 22:31
I figured out what it is. The script was failing on an svg tag on the page. Removing the svg fixes the issue. Here's a bit more detail of the error as reported by firefox: "Error TypeError: g[h].href.toLowerCase is not a function while analyzing page."

**Comment by madrobby** [comment] 2011-01-26 22:47
With the latest commit, you'll now get much better debug information you can paste in here; also fixed an issue with left-over debugging statements. https://github.com/madrobby/dom-monster/commit/7bce138c068f595f7114e8cf63fe7d8463395ffc

This version is also online!

**Comment by madrobby** [comment] 2011-01-26 22:48
(try running it again and paste the results in here!)

**Comment by madrobby** [comment] 2011-01-26 22:52
Location: http://raphaeljs.com/
User agent: Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_6; en-US) AppleWebKit/534.10 (KHTML, like Gecko) Chrome/8.0.552.237 Safari/534.10
Object.nodesTips (http://lolcathost/dom-monster/src/dommonster.js?1296082205796:452:41)
Object.performanceTips (http://lolcathost/dom-monster/src/dommonster.js?1296082205796:586:8)
http://lolcathost/dom-monster/src/dommonster.js?1296082205796:644:10

**Comment by madrobby** [comment] 2011-01-26 22:53
fix an exception that happened with SVG nodes, closed by 980c3ae1c65a1ff81a02dda52954611713028633

**Closed as completed by madrobby** 2011-01-26 22:53 UTC
